name: krishna_chatbot
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.3.0
  google_fonts: ^6.2.1
  audioplayers: ^6.4.0
  connectivity_plus: ^6.1.4
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.webp"

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/google_icon.webp
    - assets/krishna_avatar.webp
    - assets/user_avatar.webp
    - assets/krishna_bg.webp
    - assets/feather.webp
    - assets/flute.webp
    - assets/app_icon.webp
    - assets/music/soothing.mp3
    # background_music: assets/music/soothing.mp3 is taken from "Enchanting Flute" by Rakesh Chaurasia