// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz-FHIQ5Nu96G19GPkBooJoY9mhEEiQFw',
    appId: '1:845273803268:web:74394fba1e10cf7997e351',
    messagingSenderId: '845273803268',
    projectId: 'krishnachatbot-11e35',
    authDomain: 'krishnachatbot-11e35.firebaseapp.com',
    storageBucket: 'krishnachatbot-11e35.firebasestorage.app',
    measurementId: 'G-S9R8ZEGE0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7ZpjKGSE7B6tfwvPJX-IzcJR5TroY-BM',
    appId: '1:845273803268:android:ef7cb441a4376a6797e351',
    messagingSenderId: '845273803268',
    projectId: 'krishnachatbot-11e35',
    storageBucket: 'krishnachatbot-11e35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwNQyVpz1YomD8CFGxV39Cs7gEcJeOgto',
    appId: '1:845273803268:ios:6a125e66c58cd30697e351',
    messagingSenderId: '845273803268',
    projectId: 'krishnachatbot-11e35',
    storageBucket: 'krishnachatbot-11e35.firebasestorage.app',
    iosBundleId: 'com.example.krishnaChatbot',
  );
}
